### ISSUE TITLE
Download in BRSTM format

### ISSUE THREAD

**Issue by ic-scm** [pedker/BCSTM-Web-Scraper#1]
Hello, you should change this to download in BRSTM format instead of BCSTM. BRSTM is the native format on the smashcustommusic website, and downloads in other formats work by doing conversions on demand, in some cases resulting in some loss of quality. If BCSTM files are needed, you can do conversions locally using [openrevolution](https://github.com/ic-scm/openrevolution) or [VGAudio](https://github.com/Thealexbarney/VGAudio), it would also take some load off the website.

**Comment by pedker** [comment]
Hello! Thanks for telling me this; I had no idea that the other file types were converted on demand. I'll make the change ASAP.
